### ISSUE TITLE
Rationale dialog is hidden beneath permissions dialog when called from onResume

### ISSUE THREAD

**Issue by sebastian-frysztak** [QuickPermissions/QuickPermissions-Kotlin#4] opened 2018-09-01 18:27 UTC
I'm trying to integrate this library into my app and I can't get it to work properly.

After first permissions dialog appears and user selects "deny", rationale dialog should pop up -- explaining why this permission is needed, am I right? I can't get it to work, rationale dialog indeed appears, but it's behind permissions dialog, which keeps appearing over and over again. Is this intended?

**Comment by sebastian-frysztak** [comment] 2018-09-01 18:37
Update: It turns out my issue was caused by the fact that I was calling `runWithPermission` from `onResume`. Moving it to `onCreate` works, but is not desirable.

**Comment by kirtan403** [comment] 2018-09-02 06:27
Permission dialog is invoked by the system's package manager. So It will always appear on top of your app's all views. It is kind of start activity for result. So when you deny the permissions, the control returns to your activity and the dialog is shown. As you said it was behind the rational dialog, because when control returned to your activity, it calls `onResume`. And permission is not granted so it starts permission request flow. This is the intended behavior. If you try to do the same thing with the sdk's methods directly, you will see the same thing. Refer this SO question: https://stackoverflow.com/q/43680921/1820644 

Closing this issue. If you get any trouble, feel free to comment here or create the new issue.

**Closed by kirtan403** 2018-09-02 06:27 UTC
